"""Shared data contract between generation and deploy pipeline.

This file is the single source of truth for the shapes that flow through
AgentForge's backend.

Flow:
    user_prompt: str
        |
        v
    watsonx_runner.generate_agent(prompt) -> AgentGenerationResult
        |
        v
    deploy_agent.deploy_agent(result) -> DeploymentResult
        |
        v
    chat_url returned to frontend (KAN-15)
"""

from dataclasses import dataclass, field
from typing import Literal, Optional


@dataclass
class ToolFile:
    """A single Python tool file generated by LLM.

    Constraints (Orchestrate ADK hard requirements, see KAN-4 + KAN-13):
        - filename: alphanumeric + underscores only, must end in .py
        - content: must contain exactly one @tool decorator
        - content: must be async and use httpx/aiohttp for external calls

    Attributes:
        filename: Tool filename, e.g. "fetch_hn.py".
        content: Raw Python source ready to write to disk.
    """

    filename: str
    content: str


@dataclass
class AgentGenerationResult:
    """Output of watsonx_runner.generate_agent() (or bob_runner for legacy).

    Consumed by deploy_agent.deploy_agent() and returned to the FastAPI
    layer (KAN-14) for SSE progress streaming to the frontend.

    Status values:
        - "ok": YAML and all tools parsed and validated, ready to deploy
        - "validation_failed": LLM output failed ADK schema check after retries
        - "bob_error": subprocess exited non-zero or auth/license issue (legacy)
        - "api_error": watsonx.ai API call failed
        - "prompt_error": Failed to load prompt template
        - "timeout": API call or subprocess timed out

    Attributes:
        agent_yaml: Validated YAML string ready for `orchestrate agents import`.
        tools: Python tool files, one per @tool decorator.
        requirements_txt: Pinned deps, e.g. "httpx==0.27.0\\nrequests==2.32.4".
        raw_bob_output: Full LLM output, kept for debugging and demo session export.
        bob_session_id: Identifier used to export task history for judging.
        status: See above.
        errors: Human-readable error messages, empty when status == "ok".
    """

    agent_yaml: Optional[str]
    tools: list[ToolFile]
    requirements_txt: Optional[str]
    raw_bob_output: str
    bob_session_id: str
    status: Literal["ok", "validation_failed", "bob_error", "api_error", "prompt_error", "timeout"]
    errors: list[str] = field(default_factory=list)


@dataclass
class DeploymentResult:
    """Output of deploy_agent.deploy_agent().

    Status values:
        - "deployed": tools imported and agent imported successfully
        - "tool_import_failed": one or more `orchestrate tools import` calls failed
        - "agent_import_failed": tools succeeded but `orchestrate agents import` failed
        - "auth_failed": Orchestrate env not active or token expired
        - "timeout": one of the CLI calls exceeded WXO_AGENT_DEPLOYMENT_TIMEOUT

    Attributes:
        agent_name: Name as registered in Orchestrate (matches YAML `name`).
        chat_url: Direct link to the deployed agent in Orchestrate chat UI.
        tools_imported: Names of tools that successfully made it into Orchestrate.
        status: See above.
        cli_output: Combined stdout + stderr from all CLI calls, for debugging.
        errors: Human-readable error messages, empty when status == "deployed".
    """

    agent_name: str
    chat_url: str
    tools_imported: list[str]
    status: Literal[
        "deployed",
        "tool_import_failed",
        "agent_import_failed",
        "auth_failed",
        "timeout",
    ]
    cli_output: str
    errors: list[str] = field(default_factory=list)
